### Site Settings ###
title               : Gabriele Corni's blog
description         : >-                               # >- means to ignore newlines until "url:"
                      I help dreamers to reach Neptune.
                      

url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "/blog"                          # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : gabrielecorni/blog               # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
#remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Gabriele Corni
  image             : /docs/social_blur_square.png
# behance           : your_username
# dribbble          : your_username
  email             : gabriele.corni@gmail.com
# facebook          : your_username
  github            : gabrielecorni
# gitlab            : your_username
  instagram         : gabrihorns
  linkedin          : gabriele-corni
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : gabrihorns
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
